#spring配置
spring:
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-ej42ajla.bj.tencentcdb.com:10053/test?autoReconnect=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gcmysql123
    type: com.alibaba.druid.pool.DruidDataSource
  #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #ehcache缓存配置文件  
  cache:
    ehcache:
      config: ehcache.xml
  #sping boot admin
  boot:
    admin:
      client:
        url: http://localhost:80

#tomcat配置
server:
  port: 80


#logback#
logging:
  level:
    com.langsin.mapper: debug
  pattern:
    console: "%clr(%5p) %clr([%thread]) %clr(%logger{36}){cyan} %clr(:) %clr(%m%n)"

#management#
management:
  endpoints:
    web:
      exposure:
        include: "*"