spring:
    datasource:
        url: jdbc:mysql://cdb-ej42ajla.bj.tencentcdb.com:10053/mydatabase?autoReconnect=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: gcmysql123
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始化时建立物理连接连接的个数
        initialSize: 5
        # 最小连接池数量
        minIdle: 5
        # 最大连接池数量
        maxActive: 20
        # 获取连接时最大等待时间(ms)，即60s
        maxWait: 60000
        # 1.Destroy线程会检测连接的间隔时间；2.testWhileIdle的判断依据
        timeBetweenEvictionRunsMillis: 60000
        # 最小生存时间ms
        minEvictableIdleTimeMillis: 300000
        # 用来检测连接是否有效的sql
        validationQuery: SELECT 1 FROM DUAL
        # 申请连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnBorrow: false
        # 归还连接时执行validationQuery检测连接是否有效，启用会降低性能
        testOnReturn: false
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
        # 执行validationQuery检测连接是否有效，不会降低性能
        testWhileIdle: true
        # 是否缓存preparedStatement，mysql建议关闭
        poolPreparedStatements: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,wall,logback

    freemarker:
        suffix: .html
        charset: utf-8
        # 关闭缓存，模板热部署
#         cache: false
#    devtools:
#        restart:
#            additional-paths: src/main/*
mybatis:
    mapper-locations: classpath:mappers/*.xml
    # 虽然可以配置这项来进行pojo包扫描，但我更倾向于在mapper.xml写全类名
    type-aliases-package: com.myitconfig.shiro.pojo
server:
    port: 80

#日志配置
logging:
    level:
        com.langsin.mapper: debug
    pattern:
        console: "%clr(%5p) %clr([%thread]) %clr(%logger{36}){cyan} %clr(:) %clr(%m%n)"
