#spring配置
spring:
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-ej42ajla.bj.tencentcdb.com:10053/test?autoReconnect=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gcmysql123
    type: com.alibaba.druid.pool.DruidDataSource
  #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #ehcache缓存配置文件  
  cache:
    ehcache:
      config: ehcache.xml
   #redis
  redis:
    database: 0
    host: 192.168.253.128
    port: 6379
    timeout: 2000
    password:
  mvc:
       static-path-pattern: /static/**
  #spring-rabbitmq
  application:
    name: rabbitmq
  rabbitmq:
    host: 192.168.253.128
    port: 5672
    username: admin
    password: 123456
  # devtools热部署工具
 devtools:
   restart:
     additional-paths: src/main/*
  
#tomcat配置
server:
  port: 80

#日志配置
logging:
  level:
    com.langsin.mapper: debug
  pattern:
    console: "%clr(%d{yyyy.MM.dd HH:mm:ss}){faint} %clr([%5p]) %clr(%-50.80logger{50}){cyan} %clr(:){faint} %m%n"
#日志配置
logging:
  level:
    com.langsin.mapper: debug
  pattern:
    console: "%clr(%5p) %clr([%thread]) %clr(%logger{36}){cyan} %clr(:) %clr(%m%n)"

freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
