#spring配置
spring:
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-ej42ajla.bj.tencentcdb.com:10053/test?autoReconnect=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gcmysql123
    type: com.alibaba.druid.pool.DruidDataSource
  #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #ehcache缓存配置文件  
  cache:
    ehcache:
      config: ehcache.xml
  #javamail
  mail:
    host: smtp.qq.com
    username: 861106704@qq.com
    password: xmxhdgahjggibfbc
    properties:
      mail:
        smtp:
          auth: true
          statrttls:
            enable: true
            required: true
  freemarker:
    suffix: .ftl
    request-context-attribute: request


#tomcat配置
server:
  port: 80

#日志配置
logging:
  level:
    com.langsin.mapper: debug
  pattern:
    console: "%clr(%d{yyyy.MM.dd HH:mm:ss}){faint} %clr([%5p]) %clr(%-50.80logger{50}){cyan} %clr(:){faint} %m%n"

email:
  model:
    name: mail.ftl
