server:
  port: 80
#spring配置
spring:
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.253.128:3306/test?autoReconnect=false&useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: gcmysql123
    type: com.alibaba.druid.pool.DruidDataSource

  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request


#日志配置
logging:
  level:
    com.langsin.mapper: debug
  pattern:
    console: "%clr(%5p) %clr([%thread]) %clr(%logger{36}){cyan} %clr(:) %clr(%m%n)"


